[package]
name = "scraper2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = "0.11.24"
scraper = "0.12.0"
csv = "1.3.0"
#ego-tree = "0.6"
